# Generated by Django 4.2.5 on 2024-07-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('blog_name', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('content', models.TextField(max_length=500)),
            ],
        ),
    ]
