# Generated by Django 4.2.5 on 2024-07-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0002_remove_blog_blog_name_remove_blog_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_name',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
