# Generated by Django 4.2.5 on 2024-07-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0003_blog_blog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_name',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
